version: '3'
services:
  exp:
    build:
      context: .
      dockerfile: Dockerfile-exp
    volumes:
      - ./.local:/tmp/local:ro
    links:
      - echoserver
      - db
    depends_on:
      - echoserver
      - db
    environment:
      CACHE_CONTROL: max-age=60
      DATABASE_URL: postgresql://postgres:password@db/pages
      USER_ENVIRONMENT_VARIABLE_KEY: shhhhhhh

  app:
    build:
      context: .
    volumes:
      - ./src:/app:ro
      - ./.local:/tmp/local:ro
    links:
      - echoserver
      - db
    depends_on:
      - echoserver
      - db
    environment:
      CACHE_CONTROL: max-age=60
      DATABASE_URL: postgresql://postgres:password@db/pages
      USER_ENVIRONMENT_VARIABLE_KEY: shhhhhhh

  echoserver:
    # simple python server to log requests during development
    build:
      context: ./echo-server
      dockerfile: Dockerfile
    container_name: echoserver
    volumes:
      - ./echo-server:/code
    environment:
      PORT: 8989
    ports:
      - "8989:8989"

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pages"]
      interval: 10s
      timeout: 5s
      retries: 5      
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pages

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: test
    volumes:
      - ./:/app