---
############################
#  SHARED

env-cf: &env-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((production-cf-username))
  CF_PASSWORD: ((production-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: production

python-image: &python-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: python
      tag: 3.8

cf-image: &cf-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: 18fgsa/concourse-task

test: &test
  - task: test
    config:
      <<: *python-image
      inputs: [name: src]
      outputs: [name: src]
      run:
        dir: src
        path: ci/tasks/test.sh
    params:
      CC_TEST_REPORTER_ID: 449ef357d9e81688685bde0dcdd348bc764d717fa6a4c9c01562bd8037ceb665

############################
#  JOBS

jobs:

  - name: set-pipeline
    serial: true
    plan:
      - get: src
        resource: src-production
        params: {depth: 1}
        trigger: true
      - set_pipeline: federalist-build-container
        file: src/ci/federalist-pipeline.yml
        
  - name: test-pr-main
    plan:
    - get: src
      resource: pr-main
      trigger: true
      version: every

    - put: src
      resource: pr-main
      params:
        path: src
        status: pending
        base_context: concourse
        context: test-federalist-build-container

    - do: *test

    on_failure:
      put: src
      resource: pr-main
      params:
        path: src
        status: failure
        base_context: concourse
        context: test-federalist-build-container

    on_success:
      put: src
      resource: pr-main
      params:
        path: src
        status: success
        base_context: concourse
        context: test-federalist-build-container

  - name: test-production
    plan:
      - get: src
        resource: src-production
        passed: [set-pipeline]
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - do: *test
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: federalist build container tests on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: deploy
    plan:
      - get: src
        resource: src-production
        trigger: true
        params: {depth: 1}
        passed: [test-production]
      - put: build-container-image
        params:
          build: src
      - task: deploy
        config:
          <<: *cf-image
          inputs:
            - name: src
            - name: build-container-image
          run:
            dir: src
            path: ci/tasks/deploy.sh
        params:
          <<: *env-cf
          CF_APP_NAME: federalist-build-container
          CF_MANIFEST: .cloudgov/manifest.yml
          CF_VARS_FILE: .cloudgov/vars/production.yml
          CF_DOCKER_IMAGE_DIGEST: ../build-container-image/digest
          CF_DOCKER_IMAGE_REPOSITORY: ((image-repository))
          CF_DOCKER_USERNAME: ((docker-username))
          CF_DOCKER_PASSWORD: ((docker-password))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: federalist build container deployment on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: nightly-tasks-production
    plan:
      - get: src
        resource: src-production
        passed: [set-pipeline]
        params: {depth: 1}
      - get: nightly
        trigger: true
      - task: restage
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            dir: src
            path: ci/tasks/restage.sh
        params:
          <<: *env-cf
          CF_APP_NAME: federalist-build-container

############################
#  RESOURCES

resources:

  - name: src-production
    type: git
    icon: github
    source:
      uri: ((git-base-url))/((build-container-repository-path))
      branch: main

  - name: pr-main
    type: pull-request
    check_every: 1m
    source:
      repository: ((build-container-repository-path))
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: cloud-gov
      repo: pages-build-container
      access_token: ((gh-access-token))
      context_prefix: concourse

  - name: build-container-image
    type: docker-image
    source:
      repository: ((image-repository))
      tag: federalist-production
      username: ((docker-username))
      password: ((docker-password))

############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
