---
############################
#  SHARED

env-cf: &env-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((((deploy-env))-cf-username))
  CF_PASSWORD: ((((deploy-env))-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: ((deploy-env))

python-image: &python-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: python
      tag: 3.8

cf-image: &cf-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: 18fgsa/concourse-task

test: &test
  - task: test
    config:
      <<: *python-image
      inputs: [name: src]
      outputs: [name: src]
      run:
        dir: src
        path: ci/tasks/test.sh
    params:
      CC_TEST_REPORTER_ID: 449ef357d9e81688685bde0dcdd348bc764d717fa6a4c9c01562bd8037ceb665

############################
#  JOBS

jobs:

  - name: set-pipeline
    serial: true
    plan:
      - get: src
        resource: src-((deploy-env))
        params: {depth: 1}
        trigger: true
      - set_pipeline: build-container
        file: src/ci/pipeline.yml
        instance_vars:
          deploy-env: ((deploy-env))
          git-branch: ((git-branch))

  - name: test-pr-((git-branch))
    plan:
    - get: src
      resource: pr-((git-branch))
      trigger: true
      version: every

    - put: src
      resource: pr-((git-branch))
      params:
        path: src
        status: pending
        base_context: concourse
        context: test-pages-build-container-((deploy-env))

    - do: *test

    on_failure:
      put: src
      resource: pr-((git-branch))
      params:
        path: src
        status: failure
        base_context: concourse
        context: test-pages-build-container-((deploy-env))

    on_success:
      put: src
      resource: pr-((git-branch))
      params:
        path: src
        status: success
        base_context: concourse
        context: test-pages-build-container-((deploy-env))

  - name: test-((deploy-env))
    plan:
      - get: src
        resource: src-((deploy-env))
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - do: *test

    on_success:
      put: gh-status
      inputs: [src]
      params: {state: success}

    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages build container tests on ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: test-nightly-((deploy-env))
    plan:
      - get: src
        resource: src-((deploy-env))
        params: {depth: 1}
      - get: nightly
        trigger: true
      - do: *test
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED: pages build container tests on ((deploy-env))
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))

  - name: deploy-((deploy-env))
    plan:
      - get: src
        resource: src-((deploy-env))
        trigger: true
        params: {depth: 1}
        passed: [test-((deploy-env))]
      - put: build-container-image
        params:
          build: src
      - task: deploy
        config:
          <<: *cf-image
          inputs:
            - name: src
            - name: build-container-image
          run:
            dir: src
            path: ci/tasks/deploy.sh
        params:
          <<: *env-cf
          CF_APP_NAME: pages-build-container-((deploy-env))
          CF_MANIFEST: .cloudgov/manifest.yml
          CF_VARS_FILE: .cloudgov/vars/pages-((deploy-env)).yml
          CF_DOCKER_IMAGE_DIGEST: ../build-container-image/digest
          CF_DOCKER_IMAGE_REPOSITORY: ((image-repository))
          CF_DOCKER_USERNAME: ((docker-username))
          CF_DOCKER_PASSWORD: ((docker-password))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages build container deployment on ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: nightly-((deploy-env))
    plan:
      - get: src
        resource: src-((deploy-env))
        params: {depth: 1}
        passed: [test-nightly-((deploy-env))]
      - get: nightly
        trigger: true
      - put: build-container-image
        params:
          build: src
      - task: deploy
        config:
          <<: *cf-image
          inputs:
            - name: src
            - name: build-container-image
          run:
            dir: src
            path: ci/tasks/deploy.sh
        params:
          <<: *env-cf
          CF_APP_NAME: pages-build-container-((deploy-env))
          CF_MANIFEST: .cloudgov/manifest.yml
          CF_VARS_FILE: .cloudgov/vars/pages-((deploy-env)).yml
          CF_DOCKER_IMAGE_DIGEST: ../build-container-image/digest
          CF_DOCKER_IMAGE_REPOSITORY: ((image-repository))
          CF_DOCKER_USERNAME: ((docker-username))
          CF_DOCKER_PASSWORD: ((docker-password))
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED: pages build container deployment on ((deploy-env))
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))

  - name: report-success-((deploy-env))
    plan:
      - get: src
        resource: src-((deploy-env))
        trigger: true
        params: {depth: 1}
        passed: [deploy-((deploy-env))]
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed pages build containers on ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

############################
#  RESOURCES

resources:

  - name: src-((deploy-env))
    type: git
    icon: github
    source:
      uri: ((git-base-url))/((garden-build-repository-path))
      branch: ((git-branch))

  - name: pr-((git-branch))
    type: pull-request
    check_every: 1m
    source:
      repository: ((garden-build-repository-path))
      access_token: ((gh-access-token))
      base_branch: ((git-branch))
      disable_forks: true
      ignore_drafts: false

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: 18F
      repo: federalist-garden-build
      access_token: ((gh-access-token))
      context_prefix: concourse

  - name: build-container-image
    type: docker-image
    source:
      repository: ((image-repository))
      tag: pages-((deploy-env))
      username: ((docker-username))
      password: ((docker-password))


############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
